---
dependencies: []

galaxy_info:
  role_name: certbot
  namespace: usegalaxy_eu
  author: usegalaxy-eu
  description: "Certbot with custom additions"
  license: "license (BSD, MIT)"
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - networking
    - system
    - web
    - certbot
    - letsencrypt
    - encryption
    - certificates
    - ssl
    - https
