---
- name: Install certbot into virtualenv
  ansible.builtin.pip:
    name:
      - certbot
      - idna<2.8,>=2.5
    virtualenv_command: "{{ certbot_virtualenv_command | default(pip_virtualenv_command | default(omit)) }}"
    virtualenv: "{{ certbot_dir }}"

- name: Install certbot DNS provider
  ansible.builtin.pip:
    name:
      - "certbot-dns-{{ certbot_dns_provider }}"
    virtualenv_command: "{{ certbot_virtualenv_command | default(pip_virtualenv_command | default(omit)) }}"
    virtualenv: "{{ certbot_dir }}"
  when: certbot_dns_provider is defined

- name: Set Certbot script variable.
  ansible.builtin.set_fact:
    certbot_script: "{{ certbot_dir }}/bin/certbot"
